### ISSUE TITLE
Output of i2e function

### ISSUE THREAD

**Issue by MatRegen** [bquast/gvc#2]
It seems like some of the output of the `i2e` command produces a false output. In the case of Sweden, one receives values of up to **12825**, which, given the underlying concept of a VAX ratio or vertical specialisation ratios in general, seems unrealistic.
Attached, the output generated by `i2e` for the year 2011.
<img width="200" alt="screen shot 2018-05-07 at 12 26 32" src="https://user-images.githubusercontent.com/39051319/39697668-058b2c2e-51f2-11e8-9edf-e832da2c9a7e.png">

**Comment by bquast** [comment]
These are in levels, not shares.
